[features]
seeds = false
skip-lint = false
[programs.localnet]
bridge_solana = "Fc8Kj9zkE7fLuLnpxZyArs3oJj3EKuaLj9XNGQ2GQbwY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/user0/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
